# Generated by Django 5.1.6 on 2026-08-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadoExtracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(choices=[('oi', 'oi'), ('geral', 'geral'), ('giga_mais', 'giga_mais'), ('janeiro_2026', 'janeiro_2026'), ('mailing_2026', 'janeiro_2026')], default='oi', max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('momento_criacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresas_na_receita_federal', models.IntegerField()),
                ('empresas_com_viabilidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExecucaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(max_length=255, unique=True)),
                ('momento_criacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IniciacaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(max_length=255, unique=True)),
                ('momento_criacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(choices=[('oi', 'oi'), ('geral', 'geral'), ('giga_mais', 'giga_mais'), ('janeiro_2026', 'janeiro_2026'), ('mailing_2026', 'janeiro_2026')], default='geral', max_length=255)),
                ('log', models.TextField()),
                ('momento_criacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Execucoe_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(choices=[('oi', 'oi'), ('geral', 'geral'), ('giga_mais', 'giga_mais'), ('janeiro_2026', 'janeiro_2026'), ('mailing_2026', 'janeiro_2026')], default='geral', max_length=255)),
                ('momento_inicializacao', models.DateTimeField(auto_now_add=True)),
                ('momento_finalizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelefonesDiscados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=13, unique=True)),
                ('sucesso_chamada', models.BooleanField()),
                ('momento_chamada', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fase_Execucao_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluido', 'Concluido'), ('Em Andamento', 'Em Andamento'), ('Erro', 'Erro')], default='Pendente', max_length=255)),
                ('color', models.CharField(choices=[('primary', 'primary'), ('danger', 'danger'), ('secondary', 'secondary'), ('success', 'success')], default='primary', max_length=255)),
                ('status_execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.status_execucoe_db')),
            ],
        ),
    ]
