# Generated by Django 5.1.6 on 2026-03-02 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresas_na_receita_federal', models.IntegerField()),
                ('empresas_com_viabilidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status_Execucoe_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(choices=[('oi', 'oi'), ('geral', 'geral'), ('giga_mais', 'giga_mais'), ('janeiro_2026', 'janeiro_2026')], default='geral', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fase_Execucao_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_fase', models.CharField(max_length=255)),
                ('status_fase', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluido', 'Concluido'), ('Em Andamento', 'Em Andamento'), ('Erro', 'Erro')], default='Pendente', max_length=255)),
                ('status_execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.status_execucoe_db')),
            ],
        ),
    ]
