# Generated by Django 5.1.6 on 2026-03-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_execucoe_db',
            name='momento_finalizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='status_execucoe_db',
            name='momento_inicializacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
