# Generated by Django 5.1.6 on 2026-03-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_status_execucoe_db_momento_finalizacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fase_execucao_db',
            old_name='status_fase',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='fase_execucao_db',
            old_name='titulo_fase',
            new_name='titulo',
        ),
    ]
