# Generated by Django 5.1.6 on 2026-03-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_status_fase_fase_execucao_db_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadoExtracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('momento_criacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(choices=[('oi', 'oi'), ('geral', 'geral'), ('giga_mais', 'giga_mais'), ('janeiro_2026', 'janeiro_2026')], default='geral', max_length=255)),
                ('log', models.TextField()),
                ('momento_criacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='fase_execucao_db',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('danger', 'danger'), ('secondary', 'secondary'), ('success', 'success')], default='primary', max_length=255),
        ),
    ]
