# Generated by Django 5.1.6 on 2026-03-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_dadoextracao_log_fase_execucao_db_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_execucoe_db',
            name='momento_inicializacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
