# Generated by Django 5.1.6 on 2026-03-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_status_execucoe_db_momento_inicializacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='IniciacaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(max_length=255, unique=True)),
                ('momento_criacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dadoextracao',
            name='sistema',
            field=models.CharField(choices=[('oi', 'oi'), ('janeiro_2026', 'janeiro_2026')], default='oi', max_length=255),
        ),
    ]
