# Generated by Django 5.1.6 on 2026-03-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_iniciacaosistema_dadoextracao_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(max_length=255, unique=True)),
                ('momento_criacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
