# Generated by Django 5.1.6 on 2026-03-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_execucaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciacaosistema',
            name='infos',
            field=models.CharField(default='', max_length=255),
        ),
    ]
