# Generated by Django 5.1.6 on 2026-03-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_iniciacaosistema_infos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iniciacaosistema',
            name='infos',
        ),
    ]
