# Generated by Django 5.1.6 on 2026-04-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_remove_iniciacaosistema_infos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase_execucao_db',
            name='titulo',
            field=models.TextField(),
        ),
    ]
