# Generated by Django 5.1.6 on 2026-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_fase_execucao_db_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelefonesDiscados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=13)),
                ('sucesso_chamada', models.BooleanField()),
                ('momento_chamada', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='dadoextracao',
            name='sistema',
            field=models.CharField(choices=[('oi', 'oi'), ('geral', 'geral'), ('giga_mais', 'giga_mais'), ('janeiro_2026', 'janeiro_2026'), ('mailing_2026', 'janeiro_2026')], default='oi', max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='sistema',
            field=models.CharField(choices=[('oi', 'oi'), ('geral', 'geral'), ('giga_mais', 'giga_mais'), ('janeiro_2026', 'janeiro_2026'), ('mailing_2026', 'janeiro_2026')], default='geral', max_length=255),
        ),
        migrations.AlterField(
            model_name='status_execucoe_db',
            name='sistema',
            field=models.CharField(choices=[('oi', 'oi'), ('geral', 'geral'), ('giga_mais', 'giga_mais'), ('janeiro_2026', 'janeiro_2026'), ('mailing_2026', 'janeiro_2026')], default='geral', max_length=255),
        ),
    ]
