# Generated by Django 5.1.6 on 2026-07-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_telefonesdiscados_alter_dadoextracao_sistema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefonesdiscados',
            name='telefone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
