# Generated by Django 5.1.6 on 2026-08-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cnae',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'CNAE',
                'verbose_name_plural': 'CNAEs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='NaturezaJuridica',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Natureza Jurídica',
                'verbose_name_plural': 'Naturezas Jurídicas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('uf', models.CharField(default='', max_length=2)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='corpdata_mu_nome_87c8fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('data_inicio_atividades', models.DateField(blank=True, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('matriz_filial', models.CharField(blank=True, max_length=20, null=True)),
                ('decisor', models.CharField(blank=True, max_length=255, null=True)),
                ('situacao_cadastral', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('correio_eletronico', models.EmailField(blank=True, max_length=255, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=150, null=True)),
                ('cep', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('mei_nome_mei', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone_receita_1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone_receita_2', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone_receita_3', models.CharField(blank=True, max_length=20, null=True)),
                ('cnae_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_principal', to='corpdata.cnae')),
                ('cnaes_secundarios', models.ManyToManyField(blank=True, related_name='empresas_secundarias', to='corpdata.cnae')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='corpdata.municipio')),
                ('natureza_juridica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='corpdata.naturezajuridica')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'indexes': [models.Index(fields=['razao_social'], name='corpdata_em_razao_s_7dbf4a_idx'), models.Index(fields=['nome_fantasia'], name='corpdata_em_nome_fa_50921b_idx'), models.Index(fields=['municipio'], name='corpdata_em_municip_659df9_idx'), models.Index(fields=['cnae_fiscal'], name='corpdata_em_cnae_fi_abe970_idx'), models.Index(fields=['natureza_juridica'], name='corpdata_em_naturez_692b1c_idx')],
            },
        ),
    ]
