# Generated by Django 5.1.6 on 2026-08-20 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=150, null=True)),
                ('cep', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('tipo_viabilidade', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=30)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viabilidades', to='corpdata.municipio')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='viabilidades',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='corpdata.viabilidade'),
        ),
    ]
