# Generated by Django 5.1.6 on 2026-08-20 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpdata', '0002_viabilidade_empresa_viabilidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viabilidade',
            name='tipo_viabilidade',
        ),
        migrations.AddField(
            model_name='empresa',
            name='viabilidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_viabilidades', to='corpdata.viabilidade'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['viabilidade'], name='corpdata_em_viabili_3cab6c_idx'),
        ),
    ]
