# Generated by Django 5.1.6 on 2026-08-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpdata', '0003_remove_viabilidade_tipo_viabilidade_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='empresa',
            new_name='corpdata_em_viabili_71a24f_idx',
            old_name='corpdata_em_viabili_3cab6c_idx',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='viabilidade',
            field=models.CharField(blank=True, choices=[('', ''), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=18, null=True),
        ),
    ]
