# Generated by Django 5.1.6 on 2026-08-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpdata', '0004_rename_corpdata_em_viabili_3cab6c_idx_corpdata_em_viabili_71a24f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='viabilidades',
        ),
    ]
