# Generated by Django 5.1.6 on 2026-08-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpdata', '0005_remove_empresa_viabilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.DeleteModel(
            name='Viabilidade',
        ),
    ]
