# Generated by Django 5.1.6 on 2026-08-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpdata', '0006_alter_empresa_cnpj_delete_viabilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='mei_nome_mei',
        ),
        migrations.AddField(
            model_name='empresa',
            name='eh_mei',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
    ]
