# Generated by Django 5.1.6 on 2026-09-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpdata', '0007_remove_empresa_cpf_remove_empresa_mei_nome_mei_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_empresas', models.IntegerField(default=0)),
                ('total_empresas_mei', models.IntegerField(default=0)),
                ('total_empresas_nmei', models.IntegerField(default=0)),
                ('total_empresas_viabilidade_primaria', models.IntegerField(default=0)),
                ('total_empresas_viabilidade_secundaria', models.IntegerField(default=0)),
                ('total_empresas_viabilidade_nao_informada', models.IntegerField(default=0)),
                ('total_empresas_mei_viabilidade_primaria', models.IntegerField(default=0)),
                ('total_empresas_mei_viabilidade_secundaria', models.IntegerField(default=0)),
                ('total_empresas_mei_viabilidade_nao_informada', models.IntegerField(default=0)),
                ('total_empresas_nmei_viabilidade_primaria', models.IntegerField(default=0)),
                ('total_empresas_nmei_viabilidade_secundaria', models.IntegerField(default=0)),
                ('total_empresas_nmei_viabilidade_nao_informada', models.IntegerField(default=0)),
                ('total_empresas_credito_aprovado', models.IntegerField(default=0)),
                ('total_empresas_credito_negado', models.IntegerField(default=0)),
                ('total_empresas_credito_sem_info', models.IntegerField(default=0)),
            ],
        ),
    ]
