# Generated by Django 5.1.6 on 2026-09-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpdata', '0008_resumodados'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumodados',
            name='total_empresas_credito_aprovado_mei',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumodados',
            name='total_empresas_credito_aprovado_nmei',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumodados',
            name='total_empresas_credito_negado_mei',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumodados',
            name='total_empresas_credito_negado_nmei',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumodados',
            name='total_empresas_credito_sem_info_mei',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumodados',
            name='total_empresas_credito_sem_info_nmei',
            field=models.IntegerField(default=0),
        ),
    ]
