# Generated by Django 5.1.6 on 2026-09-02 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpdata', '0009_resumodados_total_empresas_credito_aprovado_mei_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoDadosUF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('total_empresas', models.IntegerField(default=0)),
                ('total_empresas_mei', models.IntegerField(default=0)),
                ('total_empresas_nmei', models.IntegerField(default=0)),
                ('total_empresas_viabilidade_primaria', models.IntegerField(default=0)),
                ('total_empresas_viabilidade_secundaria', models.IntegerField(default=0)),
                ('total_empresas_viabilidade_nao_informada', models.IntegerField(default=0)),
                ('total_empresas_mei_viabilidade_primaria', models.IntegerField(default=0)),
                ('total_empresas_mei_viabilidade_secundaria', models.IntegerField(default=0)),
                ('total_empresas_mei_viabilidade_nao_informada', models.IntegerField(default=0)),
                ('total_empresas_nmei_viabilidade_primaria', models.IntegerField(default=0)),
                ('total_empresas_nmei_viabilidade_secundaria', models.IntegerField(default=0)),
                ('total_empresas_nmei_viabilidade_nao_informada', models.IntegerField(default=0)),
                ('resumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumo_ufs', to='corpdata.resumodados')),
            ],
        ),
    ]
