# Generated by Django 5.1.6 on 2026-09-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpdata', '0010_resumodadosuf'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='credito',
            field=models.CharField(blank=True, choices=[('', ''), ('Aprovado', 'Aprovado'), ('Negado', 'Negado')], max_length=18, null=True),
        ),
    ]
