# Generated by Django 5.1.6 on 2026-09-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpdata', '0011_empresa_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumodadosuf',
            name='total_empresas_credito_aprovado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumodadosuf',
            name='total_empresas_credito_aprovado_mei',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumodadosuf',
            name='total_empresas_credito_aprovado_nmei',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumodadosuf',
            name='total_empresas_credito_negado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumodadosuf',
            name='total_empresas_credito_negado_mei',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumodadosuf',
            name='total_empresas_credito_negado_nmei',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumodadosuf',
            name='total_empresas_credito_sem_info',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumodadosuf',
            name='total_empresas_credito_sem_info_mei',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumodadosuf',
            name='total_empresas_credito_sem_info_nmei',
            field=models.IntegerField(default=0),
        ),
    ]
